<?php

namespace Puzzle\ExpertiseBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * StaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends PuzzleRepository
{
}
