<?php

namespace Puzzle\MediaBundle\Repository;

/**
 * AudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioRepository extends \Doctrine\ORM\EntityRepository
{
}
