<?php

namespace Puzzle\AdvertBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;
use Knp\DoctrineBehaviors\ORM\Tree\Tree;

/**
 * AdvertiserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertiserRepository extends PuzzleRepository
{
    use Tree;
}
