<?php

namespace Puzzle\AdvertBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * ArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveRepository extends PuzzleRepository
{
}
