services:
  # Twig extension
    contact.twig.extension:
        class: Puzzle\ContactBundle\Twig\ContactExtension
        arguments: [ '@doctrine.orm.entity_manager', "@knp_paginator" ]
        public: false
        tags:
            - { name: twig.extension }