<?php

namespace Puzzle\NewsletterBundle\Repository;

/**
 * FieldValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldValueRepository extends \Doctrine\ORM\EntityRepository
{
}
