<?php

namespace Puzzle\ContactBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends PuzzleRepository
{
}
