# Post
app_blog_post_list:
    path:     /post/list
    defaults: { _controller: BlogBundle:App:listPosts }

app_blog_post_show:
    path:     /post/{slug}
    defaults: { _controller: BlogBundle:App:showPost }

# Category
app_blog_category_list:
    path:     /category/list
    defaults: { _controller: BlogBundle:App:listCategories }

app_blog_category_show:
    path:     /category/{id}/show
    defaults: { _controller: BlogBundle:App:showCategory }

# Comment
app_blog_comment_list:
    path:     /post/{id}/comment/list
    defaults: { _controller: BlogBundle:App:listComments }
    
app_blog_comment_create:
    path:     /post/{id}/comment/create
    defaults: { _controller: BlogBundle:App:createComment }

app_blog_comment_update:
    path:     /comment/{id}/update
    defaults: { _controller: BlogBundle:App:updateComment }

app_blog_comment_delete:
    path:     /comment/{id}/delete
    defaults: { _controller: BlogBundle:App:deleteComment } 

app_blog_comment_vote_create:
    path:     /comment/{id}/vote/create
    defaults: { _controller: BlogBundle:App:createCommentVote } 

app_blog_comment_vote_delete:
    path:     /comment/vote/{id}/delete
    defaults: { _controller: BlogBundle:App:deleteCommentVote } 