calendar_admin:
    resource: '@CalendarBundle/Resources/config/routing/admin.yml'
    prefix:   '%admin_prefix%calendar'
    host: '%admin_host%'
    options:
        expose: true

calendar_app:
    resource: '@CalendarBundle/Resources/config/routing/app.yml'