login:
    path:   /login
    defaults: { _controller: UserBundle:App:login }
    host: '%host%' 

register:
    path:   /register
    defaults: { _controller: UserBundle:App:register }
    host: '%host%' 

show_registration_confirmation_email:
    path:   /register/confirmation-email/{email}
    defaults: { _controller: UserBundle:App:showRegistrationConfirmationEmail }
    host: '%host%' 

confirm_registration:
    path:   /register/confirm/{token}
    defaults: { _controller: UserBundle:App:confirmRegistration }
    host: '%host%' 

app_user_resetting_send_email:
    path:   /resetting/send-email
    defaults: { _controller: UserBundle:App:resettingSendEmail }
    host: '%host%'

app_user_resetting_reset:
    path:   /resetting/reset
    defaults: { _controller: UserBundle:App:resettingReset }
    host: '%host%' 

app_user_resetting_check_email:
    path:   /resetting/check-email
    defaults: { _controller: UserBundle:App:resettingCheckEmail }
    host: '%host%' 

admin_login:
    path:   '%admin_prefix%login'
    defaults: { _controller: UserBundle:Admin:login }
    host: '%admin_host%' 

login_check:
    path:   /login_check
     
logout:
    path:   /logout