# Work
app_curriculum_work_list:
    path:     /applicant/{id}/work/list
    defaults: { _controller: 'CurriculumBundle:App:listWorks' }

app_curriculum_work_show:
    path:     /work/{id}
    defaults: { _controller: 'CurriculumBundle:App:showWork' }

# Training
app_curriculum_training_list:
    path:     /applicant/{id}/training/list
    defaults: { _controller: 'CurriculumBundle:App:listTrainings' }

app_curriculum_training_show:
    path:     /training/{id}
    defaults: { _controller: 'CurriculumBundle:App:showTraining' }

# Applicant
app_curriculum_applicant_list:
    path:     /applicant/list
    defaults: { _controller: 'CurriculumBundle:App:listApplicants' }

app_curriculum_applicant_show:
    path:     /applicant/{id}
    defaults: { _controller: 'CurriculumBundle:App:showApplicant' }