services:
    # Twig extension
    blog.twig.extension:
        class: Puzzle\BlogBundle\Twig\BlogExtension
        arguments: [ '@doctrine.orm.entity_manager', "@knp_paginator" ]
        public: false
        tags:
            - { name: twig.extension }
