# Category
admin_charity_category_list:
    path:     /list
    defaults: { _controller: 'CharityBundle:Category:list' }

admin_charity_category_create:
    path:     /create
    defaults: { _controller: 'CharityBundle:Category:create' }

admin_charity_category_show:
    path:     /{id}
    defaults: { _controller: 'CharityBundle:Category:show' }

admin_charity_category_update:
    path:     /{id}/update
    defaults: { _controller: 'CharityBundle:Category:update' }
    
admin_charity_category_delete:
    path:     /{id}/delete
    defaults: { _controller: 'CharityBundle:Category:delete' }