admin_charity_cause_list:
    path:     /list
    defaults: { _controller: 'CharityBundle:Cause:list' }

admin_charity_cause_create:
    path:     /create
    defaults: { _controller: 'CharityBundle:Cause:create' }
    
admin_charity_cause_update:
    path:     /{id}/update
    defaults: { _controller: 'CharityBundle:Cause:update' }

admin_charity_cause_delete:
    path:     /{id}/delete
    defaults: { _controller: 'CharityBundle:Cause:delete' }