admin_charity_volunteer_list:
    path:     /list
    defaults: { _controller: 'CharityBundle:Volunteer:list' }

admin_charity_volunteer_create:
    path:     /create
    defaults: { _controller: 'CharityBundle:Volunteer:create' }
    
admin_charity_volunteer_update:
    path:     /{id}/update
    defaults: { _controller: 'CharityBundle:Volunteer:update' }

admin_charity_volunteer_delete:
    path:     /{id}/delete
    defaults: { _controller: 'CharityBundle:Volunteer:delete' }