<?php

namespace Puzzle\StaticBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends PuzzleRepository
{
}
