<?php

namespace Puzzle\StaticBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends PuzzleRepository
{
}
