<?php

namespace Puzzle\CharityBundle\Repository;

/**
 * DonationLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationLineRepository extends \Doctrine\ORM\EntityRepository
{
}
