<?php

namespace Puzzle\CharityBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * DonationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationRepository extends PuzzleRepository
{
}
