# Category
admin_learning_category_list:
    path:     /list
    defaults: { _controller: 'LearningBundle:Category:list' }

admin_learning_category_create:
    path:     /create
    defaults: { _controller: 'LearningBundle:Category:create' }

admin_learning_category_show:
    path:     /{id}
    defaults: { _controller: 'LearningBundle:Category:show' }

admin_learning_category_update:
    path:     /{id}/update
    defaults: { _controller: 'LearningBundle:Category:update' }
    
admin_learning_category_delete:
    path:     /{id}/delete
    defaults: { _controller: 'LearningBundle:Category:delete' }