<?php

namespace Puzzle\NewsletterBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends PuzzleRepository
{
}
