<?php

namespace Puzzle\CalendarBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends PuzzleRepository
{
}
