<?php

namespace Puzzle\CalendarBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * MomentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MomentRepository extends PuzzleRepository
{
}
