<?php

namespace Puzzle\CurriculumBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * ApplicantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicantRepository extends PuzzleRepository
{
}
