charity_admin:
    resource: '@CharityBundle/Resources/config/routing/admin.yml'
    prefix:   '%admin_prefix%charity'
    host: '%admin_host%'
    options:
        expose: true

charity_app:
    resource: '@CharityBundle/Resources/config/routing/app.yml'
    prefix:   '/charity'
    host: '%host%'
    options:
        expose: true