services:
    charity.member.listener:
        class: Puzzle\CharityBundle\Listener\MemberListener
        arguments: [ '@doctrine.orm.entity_manager', '@router', '@mailer', '@twig', '@translator', '%user.registration.address%' ]
        tags:
            - { name: kernel.event_listener, event: "user.created", method: onCreatedUser }
            - { name: kernel.event_listener, event: "charity.member.created", method: onCreated }
            - { name: kernel.event_listener, event: "charity.member.enabled", method: onEnabled }

    charity.donation.listener:
        class: Puzzle\CharityBundle\Listener\DonationListener
        arguments: [ '@doctrine.orm.entity_manager', '@router', '@mailer', '@twig', '@translator', '%user.registration.address%' ]
        tags:
            - { name: kernel.event_listener, event: "charity.donation.paid", method: onPaid }

    # Twig extension
    charity.twig.extension:
        class: Puzzle\CharityBundle\Twig\CharityExtension
        arguments: [ '@doctrine.orm.entity_manager', "@knp_paginator" ]
        public: false
        tags:
            - { name: twig.extension }
