parameters:
    scheduling.manager.class: Puzzle\SchedulingBundle\Service\SchedulingManager
    scheduling.cron.class: Puzzle\SchedulingBundle\Service\SchedulingCron
    scheduling.tools.class: Puzzle\SchedulingBundle\Service\SchedulingTools
    scheduling.listener.class: Puzzle\SchedulingBundle\Listener\SchedulingListener
    
services:
    scheduling.cron:
        class: "%scheduling.cron.class%"
        arguments: ["@doctrine"]
    
    scheduling.tools:
        class: "%scheduling.tools.class%"
        
    scheduling.manager:
        class: "%scheduling.manager.class%"
        arguments: ["@doctrine.orm.entity_manager", "@scheduling.cron", "@scheduling.tools"]

    scheduling.listener:
        class: "%scheduling.listener.class%"
        arguments: ["@doctrine.orm.entity_manager", "@scheduling.manager", "@scheduling.cron", "@scheduling.tools"]
        tags:
            - { name: kernel.event_listener, event: "scheduling.schedule", method: onSchedule }
            - { name: kernel.event_listener, event: "scheduling.unschedule", method: onUnschedule }