# Moment
app_calendar_moment_list:
    path:     /moment/list
    defaults: { _controller: CalendarBundle:App:listMoments }

app_calendar_moment_show:
    path:     /moment/{id}/show
    defaults: { _controller: CalendarBundle:App:showMoment }

# Agenda
app_calendar_agenda_list:
    path:     /agenda/list
    defaults: { _controller: CalendarBundle:App:listAgendas }

app_calendar_agenda_show:
    path:     /agenda/{id}/show
    defaults: { _controller: CalendarBundle:App:showAgenda }


# Comment
app_calendar_comment_list:
    path:     /moment/{id}/comment/list
    defaults: { _controller: CalendarBundle:App:listComments }
    
app_calendar_comment_create:
    path:     /moment/{id}/comment/create
    defaults: { _controller: CalendarBundle:App:createComment }

app_calendar_comment_update:
    path:     /comment/{id}/update
    defaults: { _controller: CalendarBundle:App:updateComment }

app_calendar_comment_delete:
    path:     /comment/{id}/delete
    defaults: { _controller: CalendarBundle:App:deleteComment } 

app_calendar_comment_vote_create:
    path:     /comment/{id}/vote/create
    defaults: { _controller: CalendarBundle:App:createCommentVote } 

app_calendar_comment_vote_delete:
    path:     /comment/vote/{id}/delete
    defaults: { _controller: CalendarBundle:App:deleteCommentVote } 