# Moment
app_calendar_moment_list:
    path:     /moment/list
    defaults: { _controller: CalendarBundle:App:listMoments }

app_calendar_moment_show:
    path:     /moment/{id}/show
    defaults: { _controller: CalendarBundle:App:showMoment }

# Agenda
app_calendar_agenda_list:
    path:     /agenda/list
    defaults: { _controller: CalendarBundle:App:listAgendas }

app_calendar_agenda_show:
    path:     /agenda/{id}/show
    defaults: { _controller: CalendarBundle:App:showAgenda }
