<?php

namespace Puzzle\AdminBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCategoryRepository extends PuzzleRepository
{
}
