<?php

namespace Puzzle\AdminBundle\Repository;

/**
 * ArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogArchiveRepository extends \Doctrine\ORM\EntityRepository
{
}
