<?php

namespace Puzzle\AdminBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends PuzzleRepository
{
}
