<?php

namespace Puzzle\AdminBundle\Repository;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends PuzzleRepository
{
}
