<?php

namespace Puzzle\LearningBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends PuzzleRepository
{
}
